version: '3.5'

services:
  redis-cache:
    image: redis
    container_name: cache
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    container_name: db_psql
  backend:
    build: './backend'
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/app/logs.txt
    environment:
      - REDIS=cache
      - DB_USERNAME=testuser
      - DB_PASSWORD=testpass 
      - DB_HOST=db_psql
    depends_on: 
      - db
  frontend:
    build: './frontend'
    ports:
      - 5000:5000
